### ISSUE TITLE
Add ability to comment

### ISSUE THREAD

**Issue by wdoug** [codefordenver/rmfu-feed#11]
> As a general user, I want an ability to view comments on posts, so that I can comment accordingly and participate in the RMFU policy process.

**Comment by haydenevans** [comment]
Were we using something like Disqus for commenting functionality?

**Comment by dviramontes** [comment]
deemed high priority by product owner

**Comment by dviramontes** [comment]
@brettevans, you can probably start looking into this without the article branch.
The details of how to hookup https://disqus.com/ on a static page. You can even try it on any route `/#/profile` or whatever.
