### ISSUE TITLE
List view of articles

### ISSUE THREAD

**Issue by wdoug** [codefordenver/rmfu-feed#16]
As a user, I need the ability to see a list of the posts that have been added, so that I know what is being discussed.

**Comment by switzersc** [comment]
need updated mockup for this

**Comment by jenshurley** [comment]
Maybe posts look like Material-esque cards. Very roughly as below. But with colors. 
![rmfu_list_posts_as_cards_mock](https://cloud.githubusercontent.com/assets/7987959/11077134/aee94750-87bb-11e5-93e3-094398ed5103.jpeg)

Maybe they are like a table view, as they are in [CfA forum](http://forum.codeforamerica.org/)
![rmfu_list_posts_mock](https://cloud.githubusercontent.com/assets/7987959/11077137/b1b84a9e-87bb-11e5-83ce-ec898ee2878a.jpeg)

**Comment by wdoug** [comment]
Sweet mockups @jenshurley

**Comment by jenshurley** [comment]
MVP
![rmfu_custom_feed_articles_mvp](https://cloud.githubusercontent.com/assets/7987959/11132810/672ae0d2-894f-11e5-970e-5018682d20c4.jpeg)

With labels and comments 

![rmfu_custom_feed_articles_2](https://cloud.githubusercontent.com/assets/7987959/11132821/739ca0a8-894f-11e5-8f7e-6989bfd42b1f.jpeg)

**Comment by zacharyrose** [comment]
See http://localhost:3449/#/feed
