### ISSUE TITLE
Add fields to User Model

### ISSUE THREAD

**Issue by dviramontes** [codefordenver/rmfu-feed#4]
As per this [doc](https://docs.google.com/document/d/1tR-d-3zbE89cwxQKR46QV4CxpXj7FmUR1u5XQCrKxyw/edit) by RMFU staff, we need to support:

> First and Last name, email, zip, overview of farming interests (word cloud, checked box, etc).

in the User model.

**Comment by switzersc** [comment]
we already have email and pw. first and last name important, others are nice to have

**Comment by dviramontes** [comment]
potential user interest group: 

Fruit/Vegetable, 
ranch/meat, 
commodity, 
small grain, 
water/soil, 
conservation, 
farm technology,
 energy

**Comment by dviramontes** [comment]
so the sign-up view will stay the same
we will use the http://localhost:3000/#/profile
view to update user fields

**Comment by dviramontes** [comment]
using chosen for interest group selection:
https://harvesthq.github.io/chosen/
because its got bindings to cljs: http://cljsjs.github.io/
