### ISSUE TITLE
Add an About page

### ISSUE THREAD

**Issue by dviramontes** [codefordenver/rmfu-feed#45]
should say some words about RMFU and Code For Denver

**Comment by haydenevans** [comment]
Is this About page for the project/feed in general? Should this include some sort of guide on how to use the Feed as well?

**Comment by haydenevans** [comment]
Taking About RMFU content from: https://www.rmfu.org/about-us/

**Comment by haydenevans** [comment]
Taking About Code for Denver content from: http://www.codefordenver.org

**Comment by dviramontes** [comment]
@haydenevans do you need help with this ?
any blockers?
