### ISSUE TITLE
Figure out production hosting

### ISSUE THREAD

**Issue by wdoug** [codefordenver/rmfu-feed#68]
As a RMFU staff member, I would like The Feed to be secure and fast to respond, so there isn't an issue with user data, or users not using the service because of slow response times.

**Comment by wdoug** [comment]
It seems like the simplest would just be to add a heroku hobby plan ($7/month) to the pipeline as a manual deploy from stage.

**Comment by dviramontes** [comment]
Waiting to verify with RMFU tomorrow after demo
