### ISSUE TITLE
Revise mockups for initial iteration

### ISSUE THREAD

**Issue by nibble128** [codefordenver/rmfu-feed#9]

**Comment by nibble128** [comment]
https://drive.google.com/open?id=1tR-d-3zbE89cwxQKR46QV4CxpXj7FmUR1u5XQCrKxyw

**Comment by haydenevans** [comment]
Mockups in Slides: https://docs.google.com/presentation/d/1hHe-Igltn8h5wA-WZPgYcld4GXIBYixLKb6uzHNxKoc/edit#slide=id.gd1034a93d_2_45
